# Optimized config for Railway deployment
recipe: default.v1
assistant_id: ev_charger_railway_bot

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3  # Reduced for memory efficiency
  - name: DIETClassifier
    epochs: 30  # Balanced for performance
    transformer_size: 128  # Optimized size
    number_of_transformer_layers: 1
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 30
    transformer_size: 128
    constrain_similarities: true

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
  - name: TEDPolicy
    max_history: 4  # Reduced memory usage
    epochs: 30
    transformer_size: 128
    number_of_transformer_layers: 1
    constrain_similarities: true