FROM rasa/rasa-sdk:3.6.0

# Set working directory
WORKDIR /app

# Copy requirements for actions
COPY requirements-actions.txt /app/

# Install dependencies
USER root
RUN pip install --no-cache-dir -r requirements-actions.txt
USER 1001

# Copy actions
COPY ./actions /app/actions

# Expose port
EXPOSE 5055

# Start actions server
CMD ["start", "--actions", "actions"]